version: 0.2

env:
  variables:
    ENV_VARIABLE_NAME: "value"
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - npm install
  pre_build:
    commands:
      - echo "Preparing the build environment..."
  build:
    commands:
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aes3232:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aes3232:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
